// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Dashboard.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1Dashboard
    {
        public readonly double? Images_count;
        public readonly double? Ips_count;
        public readonly double? Ips_unused;
        public readonly double? Placement_groups_count;
        public readonly double? Private_nics_count;
        public readonly double? Running_servers_count;
        public readonly double? Security_groups_count;
        public readonly ImmutableDictionary<string, double>? Servers_by_types;
        public readonly double? Servers_count;
        public readonly double? Snapshots_count;
        public readonly double? Volumes_b_ssd_count;
        public readonly double? Volumes_b_ssd_total_size;
        public readonly double? Volumes_count;
        public readonly double? Volumes_l_ssd_count;
        public readonly double? Volumes_l_ssd_total_size;

        [OutputConstructor]
        private ScalewayInstanceV1Dashboard(
            double? images_count,

            double? ips_count,

            double? ips_unused,

            double? placement_groups_count,

            double? private_nics_count,

            double? running_servers_count,

            double? security_groups_count,

            ImmutableDictionary<string, double>? servers_by_types,

            double? servers_count,

            double? snapshots_count,

            double? volumes_b_ssd_count,

            double? volumes_b_ssd_total_size,

            double? volumes_count,

            double? volumes_l_ssd_count,

            double? volumes_l_ssd_total_size)
        {
            Images_count = images_count;
            Ips_count = ips_count;
            Ips_unused = ips_unused;
            Placement_groups_count = placement_groups_count;
            Private_nics_count = private_nics_count;
            Running_servers_count = running_servers_count;
            Security_groups_count = security_groups_count;
            Servers_by_types = servers_by_types;
            Servers_count = servers_count;
            Snapshots_count = snapshots_count;
            Volumes_b_ssd_count = volumes_b_ssd_count;
            Volumes_b_ssd_total_size = volumes_b_ssd_total_size;
            Volumes_count = volumes_count;
            Volumes_l_ssd_count = volumes_l_ssd_count;
            Volumes_l_ssd_total_size = volumes_l_ssd_total_size;
        }
    }
}
