// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bootscripts

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-scaleway-instances/sdk/go/sclwyinst/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetBootscript(ctx *pulumi.Context, args *GetBootscriptArgs, opts ...pulumi.InvokeOption) (*GetBootscriptResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetBootscriptResult
	err := ctx.Invoke("scaleway-instances:bootscripts:getBootscript", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return rv.Defaults(), nil
}

type GetBootscriptArgs struct {
	Id string `pulumi:"id"`
	// The zone you want to target
	Zone string `pulumi:"zone"`
}

type GetBootscriptResult struct {
	Bootscript *ScalewayInstanceV1Bootscript `pulumi:"bootscript"`
}

// Defaults sets the appropriate defaults for GetBootscriptResult
func (val *GetBootscriptResult) Defaults() *GetBootscriptResult {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Bootscript = tmp.Bootscript.Defaults()

	return &tmp
}

func GetBootscriptOutput(ctx *pulumi.Context, args GetBootscriptOutputArgs, opts ...pulumi.InvokeOption) GetBootscriptResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetBootscriptResultOutput, error) {
			args := v.(GetBootscriptArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv GetBootscriptResult
			secret, err := ctx.InvokePackageRaw("scaleway-instances:bootscripts:getBootscript", args, &rv, "", opts...)
			if err != nil {
				return GetBootscriptResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(GetBootscriptResultOutput)
			if secret {
				return pulumi.ToSecret(output).(GetBootscriptResultOutput), nil
			}
			return output, nil
		}).(GetBootscriptResultOutput)
}

type GetBootscriptOutputArgs struct {
	Id pulumi.StringInput `pulumi:"id"`
	// The zone you want to target
	Zone pulumi.StringInput `pulumi:"zone"`
}

func (GetBootscriptOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBootscriptArgs)(nil)).Elem()
}

type GetBootscriptResultOutput struct{ *pulumi.OutputState }

func (GetBootscriptResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetBootscriptResult)(nil)).Elem()
}

func (o GetBootscriptResultOutput) ToGetBootscriptResultOutput() GetBootscriptResultOutput {
	return o
}

func (o GetBootscriptResultOutput) ToGetBootscriptResultOutputWithContext(ctx context.Context) GetBootscriptResultOutput {
	return o
}

func (o GetBootscriptResultOutput) Bootscript() ScalewayInstanceV1BootscriptPtrOutput {
	return o.ApplyT(func(v GetBootscriptResult) *ScalewayInstanceV1Bootscript { return v.Bootscript }).(ScalewayInstanceV1BootscriptPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(GetBootscriptResultOutput{})
}
