// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Servers.Inputs
{

    public sealed class ScalewayInstanceV1VolumeServerTemplateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the snapshot on which this volume will be based
        /// </summary>
        [Input("base_snapshot")]
        public Input<string>? Base_snapshot { get; set; }

        /// <summary>
        /// Force the server to boot on this volume
        /// </summary>
        [Input("boot")]
        public Input<bool>? Boot { get; set; }

        /// <summary>
        /// UUID of the volume
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Name of the volume
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Organization ID of the volume
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// Project ID of the volume
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        /// <summary>
        /// Disk size of the volume, must be a multiple of 512 (in bytes)
        /// </summary>
        [Input("size")]
        public Input<double>? Size { get; set; }

        [Input("volume_type")]
        public Input<Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1VolumeServerTemplateVolumeType>? Volume_type { get; set; }

        public ScalewayInstanceV1VolumeServerTemplateArgs()
        {
            Boot = false;
            Volume_type = Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1VolumeServerTemplateVolumeType.LSsd;
        }
        public static new ScalewayInstanceV1VolumeServerTemplateArgs Empty => new ScalewayInstanceV1VolumeServerTemplateArgs();
    }
}
