// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../utilities";

// Export members:
export { GetBootscriptArgs, GetBootscriptOutputArgs } from "./getBootscript";
export const getBootscript: typeof import("./getBootscript").getBootscript = null as any;
export const getBootscriptOutput: typeof import("./getBootscript").getBootscriptOutput = null as any;
utilities.lazyLoad(exports, ["getBootscript","getBootscriptOutput"], () => require("./getBootscript"));

export { ListBootscriptsArgs, ListBootscriptsOutputArgs } from "./listBootscripts";
export const listBootscripts: typeof import("./listBootscripts").listBootscripts = null as any;
export const listBootscriptsOutput: typeof import("./listBootscripts").listBootscriptsOutput = null as any;
utilities.lazyLoad(exports, ["listBootscripts","listBootscriptsOutput"], () => require("./listBootscripts"));


// Export enums:
export * from "../types/enums/bootscripts";
