// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package dashboard

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-scaleway-instances/sdk/go/sclwyinst/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDashboard(ctx *pulumi.Context, args *GetDashboardArgs, opts ...pulumi.InvokeOption) (*GetDashboardResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDashboardResult
	err := ctx.Invoke("scaleway-instances:dashboard:getDashboard", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetDashboardArgs struct {
	// The zone you want to target
	Zone string `pulumi:"zone"`
}

type GetDashboardResult struct {
	Items ScalewayInstanceV1GetDashboardResponse `pulumi:"items"`
}

func GetDashboardOutput(ctx *pulumi.Context, args GetDashboardOutputArgs, opts ...pulumi.InvokeOption) GetDashboardResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDashboardResult, error) {
			args := v.(GetDashboardArgs)
			r, err := GetDashboard(ctx, &args, opts...)
			var s GetDashboardResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDashboardResultOutput)
}

type GetDashboardOutputArgs struct {
	// The zone you want to target
	Zone pulumi.StringInput `pulumi:"zone"`
}

func (GetDashboardOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDashboardArgs)(nil)).Elem()
}

type GetDashboardResultOutput struct{ *pulumi.OutputState }

func (GetDashboardResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDashboardResult)(nil)).Elem()
}

func (o GetDashboardResultOutput) ToGetDashboardResultOutput() GetDashboardResultOutput {
	return o
}

func (o GetDashboardResultOutput) ToGetDashboardResultOutputWithContext(ctx context.Context) GetDashboardResultOutput {
	return o
}

func (o GetDashboardResultOutput) Items() ScalewayInstanceV1GetDashboardResponseOutput {
	return o.ApplyT(func(v GetDashboardResult) ScalewayInstanceV1GetDashboardResponse { return v.Items }).(ScalewayInstanceV1GetDashboardResponseOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDashboardResultOutput{})
}
