// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Servers.Outputs
{

    /// <summary>
    /// Additional volume constraints
    /// </summary>
    [OutputType]
    public sealed class ScalewayInstanceV1ServerTypePerVolumeConstraintProperties
    {
        /// <summary>
        /// Local SSD volumes
        /// </summary>
        public readonly Outputs.ScalewayInstanceV1ServerTypePerVolumeConstraintPropertiesLSsdProperties? LSsd;

        [OutputConstructor]
        private ScalewayInstanceV1ServerTypePerVolumeConstraintProperties(Outputs.ScalewayInstanceV1ServerTypePerVolumeConstraintPropertiesLSsdProperties? lSsd)
        {
            LSsd = lSsd;
        }
    }
}
