// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Servers.Outputs
{

    /// <summary>
    /// Capabilities
    /// </summary>
    [OutputType]
    public sealed class ScalewayInstanceV1ServerTypeCapabilitiesProperties
    {
        /// <summary>
        /// True if server supports block storage
        /// </summary>
        public readonly bool? Block_storage;
        /// <summary>
        /// List of supported boot types
        /// </summary>
        public readonly ImmutableArray<Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ServerTypeCapabilitiesPropertiesBootTypesItem> Boot_types;

        [OutputConstructor]
        private ScalewayInstanceV1ServerTypeCapabilitiesProperties(
            bool? block_storage,

            ImmutableArray<Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ServerTypeCapabilitiesPropertiesBootTypesItem> boot_types)
        {
            Block_storage = block_storage;
            Boot_types = boot_types;
        }
    }
}
