// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Servers.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1ServerType
    {
        /// <summary>
        /// Alternative instance name if any
        /// </summary>
        public readonly ImmutableArray<string> Alt_names;
        /// <summary>
        /// CPU architecture
        /// </summary>
        public readonly Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ServerTypeArch? Arch;
        /// <summary>
        /// True if it is a baremetal instance
        /// </summary>
        public readonly bool? Baremetal;
        /// <summary>
        /// Capabilities
        /// </summary>
        public readonly Outputs.ScalewayInstanceV1ServerTypeCapabilitiesProperties? Capabilities;
        /// <summary>
        /// Number of GPU
        /// </summary>
        public readonly double? Gpu;
        /// <summary>
        /// Hourly price in Euro
        /// </summary>
        public readonly double? Hourly_price;
        /// <summary>
        /// Estimated monthly price, for a 30 days month, in Euro
        /// </summary>
        public readonly double? Monthly_price;
        /// <summary>
        /// Number of CPU
        /// </summary>
        public readonly double? Ncpus;
        /// <summary>
        /// Network available for the instance
        /// </summary>
        public readonly Outputs.ScalewayInstanceV1ServerTypeNetworkProperties? Network;
        /// <summary>
        /// Additional volume constraints
        /// </summary>
        public readonly Outputs.ScalewayInstanceV1ServerTypePerVolumeConstraintProperties? Per_volume_constraint;
        /// <summary>
        /// Available RAM in bytes
        /// </summary>
        public readonly double? Ram;
        /// <summary>
        /// Initial volume constraints
        /// </summary>
        public readonly Outputs.ScalewayInstanceV1ServerTypeVolumesConstraintProperties? Volumes_constraint;

        [OutputConstructor]
        private ScalewayInstanceV1ServerType(
            ImmutableArray<string> alt_names,

            Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ServerTypeArch? arch,

            bool? baremetal,

            Outputs.ScalewayInstanceV1ServerTypeCapabilitiesProperties? capabilities,

            double? gpu,

            double? hourly_price,

            double? monthly_price,

            double? ncpus,

            Outputs.ScalewayInstanceV1ServerTypeNetworkProperties? network,

            Outputs.ScalewayInstanceV1ServerTypePerVolumeConstraintProperties? per_volume_constraint,

            double? ram,

            Outputs.ScalewayInstanceV1ServerTypeVolumesConstraintProperties? volumes_constraint)
        {
            Alt_names = alt_names;
            Arch = arch;
            Baremetal = baremetal;
            Capabilities = capabilities;
            Gpu = gpu;
            Hourly_price = hourly_price;
            Monthly_price = monthly_price;
            Ncpus = ncpus;
            Network = network;
            Per_volume_constraint = per_volume_constraint;
            Ram = ram;
            Volumes_constraint = volumes_constraint;
        }
    }
}
