// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Servers.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1ServerTypeNetworkInterface
    {
        /// <summary>
        /// Maximum internal bandwidth in bits per seconds
        /// </summary>
        public readonly double? InternalBandwidth;
        /// <summary>
        /// Maximum internet bandwidth in bits per seconds
        /// </summary>
        public readonly double? InternetBandwidth;

        [OutputConstructor]
        private ScalewayInstanceV1ServerTypeNetworkInterface(
            double? internalBandwidth,

            double? internetBandwidth)
        {
            InternalBandwidth = internalBandwidth;
            InternetBandwidth = internetBandwidth;
        }
    }
}
