// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Servers.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1Image
    {
        public readonly Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ImageArch? Arch;
        /// <summary>
        /// (RFC 3339 format)
        /// </summary>
        public readonly string? CreationDate;
        public readonly Outputs.ScalewayInstanceV1Bootscript? DefaultBootscript;
        public readonly ImmutableDictionary<string, Outputs.ScalewayInstanceV1Volume>? ExtraVolumes;
        public readonly string? FromServer;
        public readonly string? Id;
        /// <summary>
        /// (RFC 3339 format)
        /// </summary>
        public readonly string? ModificationDate;
        public readonly string Name;
        public readonly string? Organization;
        public readonly string Project;
        public readonly bool? Public;
        public readonly Outputs.ScalewayInstanceV1VolumeSummary RootVolume;
        public readonly Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ImageState? State;
        public readonly ImmutableArray<string> Tags;
        public readonly string? Zone;

        [OutputConstructor]
        private ScalewayInstanceV1Image(
            Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ImageArch? arch,

            string? creationDate,

            Outputs.ScalewayInstanceV1Bootscript? defaultBootscript,

            ImmutableDictionary<string, Outputs.ScalewayInstanceV1Volume>? extraVolumes,

            string? fromServer,

            string? id,

            string? modificationDate,

            string name,

            string? organization,

            string project,

            bool? @public,

            Outputs.ScalewayInstanceV1VolumeSummary rootVolume,

            Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ImageState? state,

            ImmutableArray<string> tags,

            string? zone)
        {
            Arch = arch;
            CreationDate = creationDate;
            DefaultBootscript = defaultBootscript;
            ExtraVolumes = extraVolumes;
            FromServer = fromServer;
            Id = id;
            ModificationDate = modificationDate;
            Name = name;
            Organization = organization;
            Project = project;
            Public = @public;
            RootVolume = rootVolume;
            State = state;
            Tags = tags;
            Zone = zone;
        }
    }
}
