// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Servers.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1ServerType
    {
        /// <summary>
        /// Alternative instance name if any
        /// </summary>
        public readonly ImmutableArray<string> AltNames;
        /// <summary>
        /// CPU architecture
        /// </summary>
        public readonly Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ServerTypeArch? Arch;
        /// <summary>
        /// True if it is a baremetal instance
        /// </summary>
        public readonly bool? Baremetal;
        /// <summary>
        /// Capabilities
        /// </summary>
        public readonly Outputs.ScalewayInstanceV1ServerTypeCapabilitiesProperties? Capabilities;
        /// <summary>
        /// Number of GPU
        /// </summary>
        public readonly double? Gpu;
        /// <summary>
        /// Hourly price in Euro
        /// </summary>
        public readonly double? HourlyPrice;
        /// <summary>
        /// Estimated monthly price, for a 30 days month, in Euro
        /// </summary>
        public readonly double? MonthlyPrice;
        /// <summary>
        /// Number of CPU
        /// </summary>
        public readonly double? Ncpus;
        /// <summary>
        /// Network available for the instance
        /// </summary>
        public readonly Outputs.ScalewayInstanceV1ServerTypeNetworkProperties? Network;
        /// <summary>
        /// Additional volume constraints
        /// </summary>
        public readonly Outputs.ScalewayInstanceV1ServerTypePerVolumeConstraintProperties? PerVolumeConstraint;
        /// <summary>
        /// Available RAM in bytes
        /// </summary>
        public readonly double? Ram;
        /// <summary>
        /// Initial volume constraints
        /// </summary>
        public readonly Outputs.ScalewayInstanceV1ServerTypeVolumesConstraintProperties? VolumesConstraint;

        [OutputConstructor]
        private ScalewayInstanceV1ServerType(
            ImmutableArray<string> altNames,

            Pulumi.ScalewayInstances.Servers.ScalewayInstanceV1ServerTypeArch? arch,

            bool? baremetal,

            Outputs.ScalewayInstanceV1ServerTypeCapabilitiesProperties? capabilities,

            double? gpu,

            double? hourlyPrice,

            double? monthlyPrice,

            double? ncpus,

            Outputs.ScalewayInstanceV1ServerTypeNetworkProperties? network,

            Outputs.ScalewayInstanceV1ServerTypePerVolumeConstraintProperties? perVolumeConstraint,

            double? ram,

            Outputs.ScalewayInstanceV1ServerTypeVolumesConstraintProperties? volumesConstraint)
        {
            AltNames = altNames;
            Arch = arch;
            Baremetal = baremetal;
            Capabilities = capabilities;
            Gpu = gpu;
            HourlyPrice = hourlyPrice;
            MonthlyPrice = monthlyPrice;
            Ncpus = ncpus;
            Network = network;
            PerVolumeConstraint = perVolumeConstraint;
            Ram = ram;
            VolumesConstraint = volumesConstraint;
        }
    }
}
