// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const PolicyMode = {
    Optional: "optional",
    Enforced: "enforced",
} as const;

export type PolicyMode = (typeof PolicyMode)[keyof typeof PolicyMode];

export const PolicyType = {
    MaxAvailability: "max_availability",
    LowLatency: "low_latency",
} as const;

export type PolicyType = (typeof PolicyType)[keyof typeof PolicyType];

export const ScalewayInstanceV1PlacementGroupPolicyMode = {
    Optional: "optional",
    Enforced: "enforced",
} as const;

export type ScalewayInstanceV1PlacementGroupPolicyMode = (typeof ScalewayInstanceV1PlacementGroupPolicyMode)[keyof typeof ScalewayInstanceV1PlacementGroupPolicyMode];

export const ScalewayInstanceV1PlacementGroupPolicyType = {
    MaxAvailability: "max_availability",
    LowLatency: "low_latency",
} as const;

export type ScalewayInstanceV1PlacementGroupPolicyType = (typeof ScalewayInstanceV1PlacementGroupPolicyType)[keyof typeof ScalewayInstanceV1PlacementGroupPolicyType];
