// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.ScalewayInstances.SecurityGroups
{
    /// <summary>
    /// The default inbound policy
    /// </summary>
    [EnumType]
    public readonly struct ScalewayInstanceV1SecurityGroupInboundDefaultPolicy : IEquatable<ScalewayInstanceV1SecurityGroupInboundDefaultPolicy>
    {
        private readonly string _value;

        private ScalewayInstanceV1SecurityGroupInboundDefaultPolicy(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static ScalewayInstanceV1SecurityGroupInboundDefaultPolicy Accept { get; } = new ScalewayInstanceV1SecurityGroupInboundDefaultPolicy("accept");
        public static ScalewayInstanceV1SecurityGroupInboundDefaultPolicy Drop { get; } = new ScalewayInstanceV1SecurityGroupInboundDefaultPolicy("drop");

        public static bool operator ==(ScalewayInstanceV1SecurityGroupInboundDefaultPolicy left, ScalewayInstanceV1SecurityGroupInboundDefaultPolicy right) => left.Equals(right);
        public static bool operator !=(ScalewayInstanceV1SecurityGroupInboundDefaultPolicy left, ScalewayInstanceV1SecurityGroupInboundDefaultPolicy right) => !left.Equals(right);

        public static explicit operator string(ScalewayInstanceV1SecurityGroupInboundDefaultPolicy value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ScalewayInstanceV1SecurityGroupInboundDefaultPolicy other && Equals(other);
        public bool Equals(ScalewayInstanceV1SecurityGroupInboundDefaultPolicy other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// The default outbound policy
    /// </summary>
    [EnumType]
    public readonly struct ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy : IEquatable<ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy>
    {
        private readonly string _value;

        private ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy Accept { get; } = new ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy("accept");
        public static ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy Drop { get; } = new ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy("drop");

        public static bool operator ==(ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy left, ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy right) => left.Equals(right);
        public static bool operator !=(ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy left, ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy right) => !left.Equals(right);

        public static explicit operator string(ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy other && Equals(other);
        public bool Equals(ScalewayInstanceV1SecurityGroupOutboundDefaultPolicy other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// Security group state
    /// </summary>
    [EnumType]
    public readonly struct ScalewayInstanceV1SecurityGroupState : IEquatable<ScalewayInstanceV1SecurityGroupState>
    {
        private readonly string _value;

        private ScalewayInstanceV1SecurityGroupState(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static ScalewayInstanceV1SecurityGroupState Available { get; } = new ScalewayInstanceV1SecurityGroupState("available");
        public static ScalewayInstanceV1SecurityGroupState Syncing { get; } = new ScalewayInstanceV1SecurityGroupState("syncing");
        public static ScalewayInstanceV1SecurityGroupState SyncingError { get; } = new ScalewayInstanceV1SecurityGroupState("syncing_error");

        public static bool operator ==(ScalewayInstanceV1SecurityGroupState left, ScalewayInstanceV1SecurityGroupState right) => left.Equals(right);
        public static bool operator !=(ScalewayInstanceV1SecurityGroupState left, ScalewayInstanceV1SecurityGroupState right) => !left.Equals(right);

        public static explicit operator string(ScalewayInstanceV1SecurityGroupState value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ScalewayInstanceV1SecurityGroupState other && Equals(other);
        public bool Equals(ScalewayInstanceV1SecurityGroupState other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// The default inbound policy
    /// </summary>
    [EnumType]
    public readonly struct SecurityGroupInboundDefaultPolicy : IEquatable<SecurityGroupInboundDefaultPolicy>
    {
        private readonly string _value;

        private SecurityGroupInboundDefaultPolicy(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static SecurityGroupInboundDefaultPolicy Accept { get; } = new SecurityGroupInboundDefaultPolicy("accept");
        public static SecurityGroupInboundDefaultPolicy Drop { get; } = new SecurityGroupInboundDefaultPolicy("drop");

        public static bool operator ==(SecurityGroupInboundDefaultPolicy left, SecurityGroupInboundDefaultPolicy right) => left.Equals(right);
        public static bool operator !=(SecurityGroupInboundDefaultPolicy left, SecurityGroupInboundDefaultPolicy right) => !left.Equals(right);

        public static explicit operator string(SecurityGroupInboundDefaultPolicy value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is SecurityGroupInboundDefaultPolicy other && Equals(other);
        public bool Equals(SecurityGroupInboundDefaultPolicy other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// The default outbound policy
    /// </summary>
    [EnumType]
    public readonly struct SecurityGroupOutboundDefaultPolicy : IEquatable<SecurityGroupOutboundDefaultPolicy>
    {
        private readonly string _value;

        private SecurityGroupOutboundDefaultPolicy(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static SecurityGroupOutboundDefaultPolicy Accept { get; } = new SecurityGroupOutboundDefaultPolicy("accept");
        public static SecurityGroupOutboundDefaultPolicy Drop { get; } = new SecurityGroupOutboundDefaultPolicy("drop");

        public static bool operator ==(SecurityGroupOutboundDefaultPolicy left, SecurityGroupOutboundDefaultPolicy right) => left.Equals(right);
        public static bool operator !=(SecurityGroupOutboundDefaultPolicy left, SecurityGroupOutboundDefaultPolicy right) => !left.Equals(right);

        public static explicit operator string(SecurityGroupOutboundDefaultPolicy value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is SecurityGroupOutboundDefaultPolicy other && Equals(other);
        public bool Equals(SecurityGroupOutboundDefaultPolicy other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// Security group state
    /// </summary>
    [EnumType]
    public readonly struct SecurityGroupState : IEquatable<SecurityGroupState>
    {
        private readonly string _value;

        private SecurityGroupState(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static SecurityGroupState Available { get; } = new SecurityGroupState("available");
        public static SecurityGroupState Syncing { get; } = new SecurityGroupState("syncing");
        public static SecurityGroupState SyncingError { get; } = new SecurityGroupState("syncing_error");

        public static bool operator ==(SecurityGroupState left, SecurityGroupState right) => left.Equals(right);
        public static bool operator !=(SecurityGroupState left, SecurityGroupState right) => !left.Equals(right);

        public static explicit operator string(SecurityGroupState value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is SecurityGroupState other && Equals(other);
        public bool Equals(SecurityGroupState other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
