// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bootscripts

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The bootscript arch
type ScalewayInstanceV1BootscriptArch string

const (
	ScalewayInstanceV1BootscriptArchX8664 = ScalewayInstanceV1BootscriptArch("x86_64")
	ScalewayInstanceV1BootscriptArchArm   = ScalewayInstanceV1BootscriptArch("arm")
)

type ScalewayInstanceV1BootscriptArchOutput struct{ *pulumi.OutputState }

func (ScalewayInstanceV1BootscriptArchOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ScalewayInstanceV1BootscriptArch)(nil)).Elem()
}

func (o ScalewayInstanceV1BootscriptArchOutput) ToScalewayInstanceV1BootscriptArchOutput() ScalewayInstanceV1BootscriptArchOutput {
	return o
}

func (o ScalewayInstanceV1BootscriptArchOutput) ToScalewayInstanceV1BootscriptArchOutputWithContext(ctx context.Context) ScalewayInstanceV1BootscriptArchOutput {
	return o
}

func (o ScalewayInstanceV1BootscriptArchOutput) ToScalewayInstanceV1BootscriptArchPtrOutput() ScalewayInstanceV1BootscriptArchPtrOutput {
	return o.ToScalewayInstanceV1BootscriptArchPtrOutputWithContext(context.Background())
}

func (o ScalewayInstanceV1BootscriptArchOutput) ToScalewayInstanceV1BootscriptArchPtrOutputWithContext(ctx context.Context) ScalewayInstanceV1BootscriptArchPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ScalewayInstanceV1BootscriptArch) *ScalewayInstanceV1BootscriptArch {
		return &v
	}).(ScalewayInstanceV1BootscriptArchPtrOutput)
}

func (o ScalewayInstanceV1BootscriptArchOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ScalewayInstanceV1BootscriptArchOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ScalewayInstanceV1BootscriptArch) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ScalewayInstanceV1BootscriptArchOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ScalewayInstanceV1BootscriptArchOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ScalewayInstanceV1BootscriptArch) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ScalewayInstanceV1BootscriptArchPtrOutput struct{ *pulumi.OutputState }

func (ScalewayInstanceV1BootscriptArchPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ScalewayInstanceV1BootscriptArch)(nil)).Elem()
}

func (o ScalewayInstanceV1BootscriptArchPtrOutput) ToScalewayInstanceV1BootscriptArchPtrOutput() ScalewayInstanceV1BootscriptArchPtrOutput {
	return o
}

func (o ScalewayInstanceV1BootscriptArchPtrOutput) ToScalewayInstanceV1BootscriptArchPtrOutputWithContext(ctx context.Context) ScalewayInstanceV1BootscriptArchPtrOutput {
	return o
}

func (o ScalewayInstanceV1BootscriptArchPtrOutput) Elem() ScalewayInstanceV1BootscriptArchOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1BootscriptArch) ScalewayInstanceV1BootscriptArch {
		if v != nil {
			return *v
		}
		var ret ScalewayInstanceV1BootscriptArch
		return ret
	}).(ScalewayInstanceV1BootscriptArchOutput)
}

func (o ScalewayInstanceV1BootscriptArchPtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ScalewayInstanceV1BootscriptArchPtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ScalewayInstanceV1BootscriptArch) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ScalewayInstanceV1BootscriptArchOutput{})
	pulumi.RegisterOutputType(ScalewayInstanceV1BootscriptArchPtrOutput{})
}
