// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Ips.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1Ip
    {
        /// <summary>
        /// (IPv4 address)
        /// </summary>
        public readonly string? Address;
        public readonly string? Id;
        public readonly string? Organization;
        public readonly string? Project;
        public readonly Outputs.GoogleProtobufStringValue? Reverse;
        public readonly Outputs.ScalewayInstanceV1ServerSummary? Server;
        public readonly ImmutableArray<string> Tags;
        public readonly string? Zone;

        [OutputConstructor]
        private ScalewayInstanceV1Ip(
            string? address,

            string? id,

            string? organization,

            string? project,

            Outputs.GoogleProtobufStringValue? reverse,

            Outputs.ScalewayInstanceV1ServerSummary? server,

            ImmutableArray<string> tags,

            string? zone)
        {
            Address = address;
            Id = id;
            Organization = organization;
            Project = project;
            Reverse = reverse;
            Server = server;
            Tags = tags;
            Zone = zone;
        }
    }
}
