// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package servers

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-scaleway-instances/sdk/go/sclwyinst/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func ListServers(ctx *pulumi.Context, args *ListServersArgs, opts ...pulumi.InvokeOption) (*ListServersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv ListServersResult
	err := ctx.Invoke("scaleway-instances:servers:listServers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type ListServersArgs struct {
	// The zone you want to target
	Zone string `pulumi:"zone"`
}

type ListServersResult struct {
	// List of servers
	Servers []ScalewayInstanceV1Server `pulumi:"servers"`
}

func ListServersOutput(ctx *pulumi.Context, args ListServersOutputArgs, opts ...pulumi.InvokeOption) ListServersResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (ListServersResult, error) {
			args := v.(ListServersArgs)
			r, err := ListServers(ctx, &args, opts...)
			var s ListServersResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(ListServersResultOutput)
}

type ListServersOutputArgs struct {
	// The zone you want to target
	Zone pulumi.StringInput `pulumi:"zone"`
}

func (ListServersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ListServersArgs)(nil)).Elem()
}

type ListServersResultOutput struct{ *pulumi.OutputState }

func (ListServersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ListServersResult)(nil)).Elem()
}

func (o ListServersResultOutput) ToListServersResultOutput() ListServersResultOutput {
	return o
}

func (o ListServersResultOutput) ToListServersResultOutputWithContext(ctx context.Context) ListServersResultOutput {
	return o
}

// List of servers
func (o ListServersResultOutput) Servers() ScalewayInstanceV1ServerArrayOutput {
	return o.ApplyT(func(v ListServersResult) []ScalewayInstanceV1Server { return v.Servers }).(ScalewayInstanceV1ServerArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(ListServersResultOutput{})
}
