// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.User_data.Outputs
{

    [OutputType]
    public sealed class ScalewayStdFile
    {
        public readonly string? Content;
        public readonly string? Content_type;
        public readonly string? Name;

        [OutputConstructor]
        private ScalewayStdFile(
            string? content,

            string? content_type,

            string? name)
        {
            Content = content;
            Content_type = content_type;
            Name = name;
        }
    }
}
