# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from enum import Enum

__all__ = [
    'ScalewayInstanceV1BootscriptArch',
]


class ScalewayInstanceV1BootscriptArch(str, Enum):
    """
    The bootscript arch
    """
    X8664 = "x86_64"
    ARM = "arm"
