// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Images.Inputs
{

    public sealed class ScalewayInstanceV1BootscriptArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The bootscript arch
        /// </summary>
        [Input("arch")]
        public Input<Pulumi.ScalewayInstances.Images.ScalewayInstanceV1BootscriptArch>? Arch { get; set; }

        /// <summary>
        /// The bootscript arguments
        /// </summary>
        [Input("bootcmdargs")]
        public Input<string>? Bootcmdargs { get; set; }

        /// <summary>
        /// Dispmay if the bootscript is the default bootscript if no other boot option is configured
        /// </summary>
        [Input("default")]
        public Input<bool>? Default { get; set; }

        /// <summary>
        /// Provide information regarding a Device Tree Binary (dtb) for use with C1 servers
        /// </summary>
        [Input("dtb")]
        public Input<string>? Dtb { get; set; }

        /// <summary>
        /// The bootscript ID
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The initrd (initial ramdisk) configuration
        /// </summary>
        [Input("initrd")]
        public Input<string>? Initrd { get; set; }

        /// <summary>
        /// The server kernel version
        /// </summary>
        [Input("kernel")]
        public Input<string>? Kernel { get; set; }

        /// <summary>
        /// The bootscript organization ID
        /// </summary>
        [Input("organization")]
        public Input<string>? Organization { get; set; }

        /// <summary>
        /// The bootscript project ID
        /// </summary>
        [Input("project")]
        public Input<string>? Project { get; set; }

        /// <summary>
        /// Provide information if the bootscript is public
        /// </summary>
        [Input("public")]
        public Input<bool>? Public { get; set; }

        /// <summary>
        /// The bootscript title
        /// </summary>
        [Input("title")]
        public Input<string>? Title { get; set; }

        /// <summary>
        /// The zone in which is the bootscript
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public ScalewayInstanceV1BootscriptArgs()
        {
            Arch = Pulumi.ScalewayInstances.Images.ScalewayInstanceV1BootscriptArch.X8664;
        }
        public static new ScalewayInstanceV1BootscriptArgs Empty => new ScalewayInstanceV1BootscriptArgs();
    }
}
