# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from ._enums import *

__all__ = [
    'ScalewayInstanceV1ServerActionRequestVolumeBackupTemplateArgs',
    'ScalewayInstanceV1ServerActionRequestVolumeBackupTemplateArgsDict',
]

MYPY = False

if not MYPY:
    class ScalewayInstanceV1ServerActionRequestVolumeBackupTemplateArgsDict(TypedDict):
        volume_type: NotRequired[pulumi.Input['ScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType']]
elif False:
    ScalewayInstanceV1ServerActionRequestVolumeBackupTemplateArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class ScalewayInstanceV1ServerActionRequestVolumeBackupTemplateArgs:
    def __init__(__self__, *,
                 volume_type: Optional[pulumi.Input['ScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType']] = None):
        if volume_type is None:
            volume_type = 'l_ssd'
        if volume_type is not None:
            pulumi.set(__self__, "volume_type", volume_type)

    @property
    @pulumi.getter(name="volumeType")
    def volume_type(self) -> Optional[pulumi.Input['ScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType']]:
        return pulumi.get(self, "volume_type")

    @volume_type.setter
    def volume_type(self, value: Optional[pulumi.Input['ScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType']]):
        pulumi.set(self, "volume_type", value)


