// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";
import * as utilities from "../utilities";

export function listImages(args: ListImagesArgs, opts?: pulumi.InvokeOptions): Promise<ListImagesResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("scaleway-instances:images:listImages", {
        "zone": args.zone,
    }, opts);
}

export interface ListImagesArgs {
    /**
     * The zone you want to target
     */
    zone: string;
}

export interface ListImagesResult {
    readonly items: outputs.images.ScalewayInstanceV1ListImagesResponse;
}

export function listImagesOutput(args: ListImagesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<ListImagesResult> {
    return pulumi.output(args).apply(a => listImages(a, opts))
}

export interface ListImagesOutputArgs {
    /**
     * The zone you want to target
     */
    zone: pulumi.Input<string>;
}
