// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Export
{
    [ScalewayInstancesResourceType("scaleway-instances:export:ExportSnapshot")]
    public partial class ExportSnapshot : global::Pulumi.CustomResource
    {
        /// <summary>
        /// S3 bucket name
        /// </summary>
        [Output("bucket")]
        public Output<string?> Bucket { get; private set; } = null!;

        /// <summary>
        /// S3 object key
        /// </summary>
        [Output("key")]
        public Output<string?> Key { get; private set; } = null!;


        /// <summary>
        /// Create a ExportSnapshot resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ExportSnapshot(string name, ExportSnapshotArgs? args = null, CustomResourceOptions? options = null)
            : base("scaleway-instances:export:ExportSnapshot", name, args ?? new ExportSnapshotArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ExportSnapshot(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("scaleway-instances:export:ExportSnapshot", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/cloudy-sky-software/pulumi-scaleway-instances",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ExportSnapshot resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ExportSnapshot Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ExportSnapshot(name, id, options);
        }
    }

    public sealed class ExportSnapshotArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// S3 bucket name
        /// </summary>
        [Input("bucket")]
        public Input<string>? Bucket { get; set; }

        /// <summary>
        /// S3 object key
        /// </summary>
        [Input("key")]
        public Input<string>? Key { get; set; }

        /// <summary>
        /// The snapshot ID
        /// </summary>
        [Input("snapshot_id")]
        public Input<string>? Snapshot_id { get; set; }

        /// <summary>
        /// The zone you want to target
        /// </summary>
        [Input("zone")]
        public Input<string>? Zone { get; set; }

        public ExportSnapshotArgs()
        {
        }
        public static new ExportSnapshotArgs Empty => new ExportSnapshotArgs();
    }
}
