// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.PrivateNics.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1GetPrivateNICResponse
    {
        public readonly Outputs.ScalewayInstanceV1PrivateNIC? Private_nic;

        [OutputConstructor]
        private ScalewayInstanceV1GetPrivateNICResponse(Outputs.ScalewayInstanceV1PrivateNIC? private_nic)
        {
            Private_nic = private_nic;
        }
    }
}
