// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const ScalewayInstanceV1SnapshotState = {
    Available: "available",
    Snapshotting: "snapshotting",
    Error: "error",
    InvalidData: "invalid_data",
    Importing: "importing",
    Exporting: "exporting",
} as const;

export type ScalewayInstanceV1SnapshotState = (typeof ScalewayInstanceV1SnapshotState)[keyof typeof ScalewayInstanceV1SnapshotState];

export const ScalewayInstanceV1SnapshotVolumeType = {
    LSsd: "l_ssd",
    BSsd: "b_ssd",
    Unified: "unified",
} as const;

export type ScalewayInstanceV1SnapshotVolumeType = (typeof ScalewayInstanceV1SnapshotVolumeType)[keyof typeof ScalewayInstanceV1SnapshotVolumeType];

export const SnapshotScalewayInstanceV1TaskStatus = {
    Pending: "pending",
    Started: "started",
    Success: "success",
    Failure: "failure",
    Retry: "retry",
} as const;

/**
 * The task status
 */
export type SnapshotScalewayInstanceV1TaskStatus = (typeof SnapshotScalewayInstanceV1TaskStatus)[keyof typeof SnapshotScalewayInstanceV1TaskStatus];

export const SnapshotState = {
    Available: "available",
    Snapshotting: "snapshotting",
    Error: "error",
    InvalidData: "invalid_data",
    Importing: "importing",
    Exporting: "exporting",
} as const;

export type SnapshotState = (typeof SnapshotState)[keyof typeof SnapshotState];

export const SnapshotVolumeType = {
    LSsd: "l_ssd",
    BSsd: "b_ssd",
    Unified: "unified",
} as const;

export type SnapshotVolumeType = (typeof SnapshotVolumeType)[keyof typeof SnapshotVolumeType];
