// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export interface ScalewayInstanceV1GetPlacementGroupResponse {
    placement_group?: outputs.placement_groups.ScalewayInstanceV1PlacementGroup;
}
/**
 * scalewayInstanceV1GetPlacementGroupResponseProvideDefaults sets the appropriate defaults for ScalewayInstanceV1GetPlacementGroupResponse
 */
export function scalewayInstanceV1GetPlacementGroupResponseProvideDefaults(val: ScalewayInstanceV1GetPlacementGroupResponse): ScalewayInstanceV1GetPlacementGroupResponse {
    return {
        ...val,
        placement_group: (val.placement_group ? outputs.placement_groups.scalewayInstanceV1PlacementGroupProvideDefaults(val.placement_group) : undefined),
    };
}

export interface ScalewayInstanceV1ListPlacementGroupsResponse {
    /**
     * List of placement groups
     */
    placement_groups?: outputs.placement_groups.ScalewayInstanceV1PlacementGroup[];
}

export interface ScalewayInstanceV1PlacementGroup {
    id?: string;
    /**
     * The placement group name
     */
    name: string;
    /**
     * The placement group organization ID
     */
    organization?: string;
    policy_mode?: enums.placement_groups.ScalewayInstanceV1PlacementGroupPolicyMode;
    /**
     * Returns true if the policy is respected, false otherwise
     */
    policy_respected?: boolean;
    policy_type?: enums.placement_groups.ScalewayInstanceV1PlacementGroupPolicyType;
    /**
     * The placement group project ID
     */
    project: string;
    /**
     * The placement group tags
     */
    tags?: string[];
    /**
     * The zone in which is the placement group
     */
    zone?: string;
}
/**
 * scalewayInstanceV1PlacementGroupProvideDefaults sets the appropriate defaults for ScalewayInstanceV1PlacementGroup
 */
export function scalewayInstanceV1PlacementGroupProvideDefaults(val: ScalewayInstanceV1PlacementGroup): ScalewayInstanceV1PlacementGroup {
    return {
        ...val,
        policy_mode: (val.policy_mode) ?? "optional",
        policy_type: (val.policy_type) ?? "max_availability",
    };
}

