// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Snapshots.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1GetSnapshotResponse
    {
        public readonly Outputs.ScalewayInstanceV1Snapshot? Snapshot;

        [OutputConstructor]
        private ScalewayInstanceV1GetSnapshotResponse(Outputs.ScalewayInstanceV1Snapshot? snapshot)
        {
            Snapshot = snapshot;
        }
    }
}
