# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'ScalewayInstanceV1GetServerTypesAvailabilityResponse',
    'ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailability',
]

@pulumi.output_type
class ScalewayInstanceV1GetServerTypesAvailabilityResponse(dict):
    def __init__(__self__, *,
                 servers: Optional[Mapping[str, 'outputs.ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailability']] = None):
        if servers is not None:
            pulumi.set(__self__, "servers", servers)

    @property
    @pulumi.getter
    def servers(self) -> Optional[Mapping[str, 'outputs.ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailability']]:
        return pulumi.get(self, "servers")


@pulumi.output_type
class ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailability(dict):
    def __init__(__self__, *,
                 availability: Optional['ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailabilityAvailability'] = None):
        if availability is None:
            availability = 'available'
        if availability is not None:
            pulumi.set(__self__, "availability", availability)

    @property
    @pulumi.getter
    def availability(self) -> Optional['ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailabilityAvailability']:
        return pulumi.get(self, "availability")


