// Code generated by pulumigen DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package placement_groups

import (
	"context"
	"reflect"

	"github.com/cloudy-sky-software/pulumi-scaleway-instances/sdk/go/sclwyinst/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

var _ = internal.GetEnvOrDefault

type ScalewayInstanceV1GetPlacementGroupResponse struct {
	Placement_group *ScalewayInstanceV1PlacementGroup `pulumi:"placement_group"`
}

// Defaults sets the appropriate defaults for ScalewayInstanceV1GetPlacementGroupResponse
func (val *ScalewayInstanceV1GetPlacementGroupResponse) Defaults() *ScalewayInstanceV1GetPlacementGroupResponse {
	if val == nil {
		return nil
	}
	tmp := *val
	tmp.Placement_group = tmp.Placement_group.Defaults()

	return &tmp
}

type ScalewayInstanceV1GetPlacementGroupResponseOutput struct{ *pulumi.OutputState }

func (ScalewayInstanceV1GetPlacementGroupResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ScalewayInstanceV1GetPlacementGroupResponse)(nil)).Elem()
}

func (o ScalewayInstanceV1GetPlacementGroupResponseOutput) ToScalewayInstanceV1GetPlacementGroupResponseOutput() ScalewayInstanceV1GetPlacementGroupResponseOutput {
	return o
}

func (o ScalewayInstanceV1GetPlacementGroupResponseOutput) ToScalewayInstanceV1GetPlacementGroupResponseOutputWithContext(ctx context.Context) ScalewayInstanceV1GetPlacementGroupResponseOutput {
	return o
}

func (o ScalewayInstanceV1GetPlacementGroupResponseOutput) Placement_group() ScalewayInstanceV1PlacementGroupPtrOutput {
	return o.ApplyT(func(v ScalewayInstanceV1GetPlacementGroupResponse) *ScalewayInstanceV1PlacementGroup {
		return v.Placement_group
	}).(ScalewayInstanceV1PlacementGroupPtrOutput)
}

type ScalewayInstanceV1ListPlacementGroupsResponse struct {
	// List of placement groups
	Placement_groups []ScalewayInstanceV1PlacementGroup `pulumi:"placement_groups"`
}

type ScalewayInstanceV1ListPlacementGroupsResponseOutput struct{ *pulumi.OutputState }

func (ScalewayInstanceV1ListPlacementGroupsResponseOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ScalewayInstanceV1ListPlacementGroupsResponse)(nil)).Elem()
}

func (o ScalewayInstanceV1ListPlacementGroupsResponseOutput) ToScalewayInstanceV1ListPlacementGroupsResponseOutput() ScalewayInstanceV1ListPlacementGroupsResponseOutput {
	return o
}

func (o ScalewayInstanceV1ListPlacementGroupsResponseOutput) ToScalewayInstanceV1ListPlacementGroupsResponseOutputWithContext(ctx context.Context) ScalewayInstanceV1ListPlacementGroupsResponseOutput {
	return o
}

// List of placement groups
func (o ScalewayInstanceV1ListPlacementGroupsResponseOutput) Placement_groups() ScalewayInstanceV1PlacementGroupArrayOutput {
	return o.ApplyT(func(v ScalewayInstanceV1ListPlacementGroupsResponse) []ScalewayInstanceV1PlacementGroup {
		return v.Placement_groups
	}).(ScalewayInstanceV1PlacementGroupArrayOutput)
}

type ScalewayInstanceV1PlacementGroup struct {
	Id *string `pulumi:"id"`
	// The placement group name
	Name string `pulumi:"name"`
	// The placement group organization ID
	Organization *string                                     `pulumi:"organization"`
	Policy_mode  *ScalewayInstanceV1PlacementGroupPolicyMode `pulumi:"policy_mode"`
	// Returns true if the policy is respected, false otherwise
	Policy_respected *bool                                       `pulumi:"policy_respected"`
	Policy_type      *ScalewayInstanceV1PlacementGroupPolicyType `pulumi:"policy_type"`
	// The placement group project ID
	Project string `pulumi:"project"`
	// The placement group tags
	Tags []string `pulumi:"tags"`
	// The zone in which is the placement group
	Zone *string `pulumi:"zone"`
}

// Defaults sets the appropriate defaults for ScalewayInstanceV1PlacementGroup
func (val *ScalewayInstanceV1PlacementGroup) Defaults() *ScalewayInstanceV1PlacementGroup {
	if val == nil {
		return nil
	}
	tmp := *val
	if tmp.Policy_mode == nil {
		policy_mode_ := ScalewayInstanceV1PlacementGroupPolicyMode("optional")
		tmp.Policy_mode = &policy_mode_
	}
	if tmp.Policy_type == nil {
		policy_type_ := ScalewayInstanceV1PlacementGroupPolicyType("max_availability")
		tmp.Policy_type = &policy_type_
	}
	return &tmp
}

type ScalewayInstanceV1PlacementGroupOutput struct{ *pulumi.OutputState }

func (ScalewayInstanceV1PlacementGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ScalewayInstanceV1PlacementGroup)(nil)).Elem()
}

func (o ScalewayInstanceV1PlacementGroupOutput) ToScalewayInstanceV1PlacementGroupOutput() ScalewayInstanceV1PlacementGroupOutput {
	return o
}

func (o ScalewayInstanceV1PlacementGroupOutput) ToScalewayInstanceV1PlacementGroupOutputWithContext(ctx context.Context) ScalewayInstanceV1PlacementGroupOutput {
	return o
}

func (o ScalewayInstanceV1PlacementGroupOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ScalewayInstanceV1PlacementGroup) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// The placement group name
func (o ScalewayInstanceV1PlacementGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v ScalewayInstanceV1PlacementGroup) string { return v.Name }).(pulumi.StringOutput)
}

// The placement group organization ID
func (o ScalewayInstanceV1PlacementGroupOutput) Organization() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ScalewayInstanceV1PlacementGroup) *string { return v.Organization }).(pulumi.StringPtrOutput)
}

func (o ScalewayInstanceV1PlacementGroupOutput) Policy_mode() ScalewayInstanceV1PlacementGroupPolicyModePtrOutput {
	return o.ApplyT(func(v ScalewayInstanceV1PlacementGroup) *ScalewayInstanceV1PlacementGroupPolicyMode {
		return v.Policy_mode
	}).(ScalewayInstanceV1PlacementGroupPolicyModePtrOutput)
}

// Returns true if the policy is respected, false otherwise
func (o ScalewayInstanceV1PlacementGroupOutput) Policy_respected() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ScalewayInstanceV1PlacementGroup) *bool { return v.Policy_respected }).(pulumi.BoolPtrOutput)
}

func (o ScalewayInstanceV1PlacementGroupOutput) Policy_type() ScalewayInstanceV1PlacementGroupPolicyTypePtrOutput {
	return o.ApplyT(func(v ScalewayInstanceV1PlacementGroup) *ScalewayInstanceV1PlacementGroupPolicyType {
		return v.Policy_type
	}).(ScalewayInstanceV1PlacementGroupPolicyTypePtrOutput)
}

// The placement group project ID
func (o ScalewayInstanceV1PlacementGroupOutput) Project() pulumi.StringOutput {
	return o.ApplyT(func(v ScalewayInstanceV1PlacementGroup) string { return v.Project }).(pulumi.StringOutput)
}

// The placement group tags
func (o ScalewayInstanceV1PlacementGroupOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ScalewayInstanceV1PlacementGroup) []string { return v.Tags }).(pulumi.StringArrayOutput)
}

// The zone in which is the placement group
func (o ScalewayInstanceV1PlacementGroupOutput) Zone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ScalewayInstanceV1PlacementGroup) *string { return v.Zone }).(pulumi.StringPtrOutput)
}

type ScalewayInstanceV1PlacementGroupPtrOutput struct{ *pulumi.OutputState }

func (ScalewayInstanceV1PlacementGroupPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ScalewayInstanceV1PlacementGroup)(nil)).Elem()
}

func (o ScalewayInstanceV1PlacementGroupPtrOutput) ToScalewayInstanceV1PlacementGroupPtrOutput() ScalewayInstanceV1PlacementGroupPtrOutput {
	return o
}

func (o ScalewayInstanceV1PlacementGroupPtrOutput) ToScalewayInstanceV1PlacementGroupPtrOutputWithContext(ctx context.Context) ScalewayInstanceV1PlacementGroupPtrOutput {
	return o
}

func (o ScalewayInstanceV1PlacementGroupPtrOutput) Elem() ScalewayInstanceV1PlacementGroupOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) ScalewayInstanceV1PlacementGroup {
		if v != nil {
			return *v
		}
		var ret ScalewayInstanceV1PlacementGroup
		return ret
	}).(ScalewayInstanceV1PlacementGroupOutput)
}

func (o ScalewayInstanceV1PlacementGroupPtrOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) *string {
		if v == nil {
			return nil
		}
		return v.Id
	}).(pulumi.StringPtrOutput)
}

// The placement group name
func (o ScalewayInstanceV1PlacementGroupPtrOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) *string {
		if v == nil {
			return nil
		}
		return &v.Name
	}).(pulumi.StringPtrOutput)
}

// The placement group organization ID
func (o ScalewayInstanceV1PlacementGroupPtrOutput) Organization() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) *string {
		if v == nil {
			return nil
		}
		return v.Organization
	}).(pulumi.StringPtrOutput)
}

func (o ScalewayInstanceV1PlacementGroupPtrOutput) Policy_mode() ScalewayInstanceV1PlacementGroupPolicyModePtrOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) *ScalewayInstanceV1PlacementGroupPolicyMode {
		if v == nil {
			return nil
		}
		return v.Policy_mode
	}).(ScalewayInstanceV1PlacementGroupPolicyModePtrOutput)
}

// Returns true if the policy is respected, false otherwise
func (o ScalewayInstanceV1PlacementGroupPtrOutput) Policy_respected() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) *bool {
		if v == nil {
			return nil
		}
		return v.Policy_respected
	}).(pulumi.BoolPtrOutput)
}

func (o ScalewayInstanceV1PlacementGroupPtrOutput) Policy_type() ScalewayInstanceV1PlacementGroupPolicyTypePtrOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) *ScalewayInstanceV1PlacementGroupPolicyType {
		if v == nil {
			return nil
		}
		return v.Policy_type
	}).(ScalewayInstanceV1PlacementGroupPolicyTypePtrOutput)
}

// The placement group project ID
func (o ScalewayInstanceV1PlacementGroupPtrOutput) Project() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) *string {
		if v == nil {
			return nil
		}
		return &v.Project
	}).(pulumi.StringPtrOutput)
}

// The placement group tags
func (o ScalewayInstanceV1PlacementGroupPtrOutput) Tags() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) []string {
		if v == nil {
			return nil
		}
		return v.Tags
	}).(pulumi.StringArrayOutput)
}

// The zone in which is the placement group
func (o ScalewayInstanceV1PlacementGroupPtrOutput) Zone() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScalewayInstanceV1PlacementGroup) *string {
		if v == nil {
			return nil
		}
		return v.Zone
	}).(pulumi.StringPtrOutput)
}

type ScalewayInstanceV1PlacementGroupArrayOutput struct{ *pulumi.OutputState }

func (ScalewayInstanceV1PlacementGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]ScalewayInstanceV1PlacementGroup)(nil)).Elem()
}

func (o ScalewayInstanceV1PlacementGroupArrayOutput) ToScalewayInstanceV1PlacementGroupArrayOutput() ScalewayInstanceV1PlacementGroupArrayOutput {
	return o
}

func (o ScalewayInstanceV1PlacementGroupArrayOutput) ToScalewayInstanceV1PlacementGroupArrayOutputWithContext(ctx context.Context) ScalewayInstanceV1PlacementGroupArrayOutput {
	return o
}

func (o ScalewayInstanceV1PlacementGroupArrayOutput) Index(i pulumi.IntInput) ScalewayInstanceV1PlacementGroupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) ScalewayInstanceV1PlacementGroup {
		return vs[0].([]ScalewayInstanceV1PlacementGroup)[vs[1].(int)]
	}).(ScalewayInstanceV1PlacementGroupOutput)
}

func init() {
	pulumi.RegisterOutputType(ScalewayInstanceV1GetPlacementGroupResponseOutput{})
	pulumi.RegisterOutputType(ScalewayInstanceV1ListPlacementGroupsResponseOutput{})
	pulumi.RegisterOutputType(ScalewayInstanceV1PlacementGroupOutput{})
	pulumi.RegisterOutputType(ScalewayInstanceV1PlacementGroupPtrOutput{})
	pulumi.RegisterOutputType(ScalewayInstanceV1PlacementGroupArrayOutput{})
}
