// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../../types/input";
import * as outputs from "../../types/output";
import * as enums from "../../types/enums";
import * as utilities from "../../utilities";

export interface ScalewayInstanceV1GetServerTypesAvailabilityResponse {
    servers?: {[key: string]: outputs.availability.ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailability};
}

export interface ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailability {
    availability?: enums.availability.ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailabilityAvailability;
}
/**
 * scalewayInstanceV1GetServerTypesAvailabilityResponseAvailabilityProvideDefaults sets the appropriate defaults for ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailability
 */
export function scalewayInstanceV1GetServerTypesAvailabilityResponseAvailabilityProvideDefaults(val: ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailability): ScalewayInstanceV1GetServerTypesAvailabilityResponseAvailability {
    return {
        ...val,
        availability: (val.availability) ?? "available",
    };
}

