// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.PrivateNics
{
    public static class ListPrivateNICs
    {
        public static Task<Outputs.ScalewayInstanceV1ListPrivateNICsResponse> InvokeAsync(ListPrivateNICsArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<Outputs.ScalewayInstanceV1ListPrivateNICsResponse>("scaleway-instances:private_nics:listPrivateNICs", args ?? new ListPrivateNICsArgs(), options.WithDefaults());

        public static Output<Outputs.ScalewayInstanceV1ListPrivateNICsResponse> Invoke(ListPrivateNICsInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<Outputs.ScalewayInstanceV1ListPrivateNICsResponse>("scaleway-instances:private_nics:listPrivateNICs", args ?? new ListPrivateNICsInvokeArgs(), options.WithDefaults());
    }


    public sealed class ListPrivateNICsArgs : global::Pulumi.InvokeArgs
    {
        [Input("serverId", required: true)]
        public string ServerId { get; set; } = null!;

        /// <summary>
        /// The zone you want to target
        /// </summary>
        [Input("zone", required: true)]
        public string Zone { get; set; } = null!;

        public ListPrivateNICsArgs()
        {
        }
        public static new ListPrivateNICsArgs Empty => new ListPrivateNICsArgs();
    }

    public sealed class ListPrivateNICsInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("serverId", required: true)]
        public Input<string> ServerId { get; set; } = null!;

        /// <summary>
        /// The zone you want to target
        /// </summary>
        [Input("zone", required: true)]
        public Input<string> Zone { get; set; } = null!;

        public ListPrivateNICsInvokeArgs()
        {
        }
        public static new ListPrivateNICsInvokeArgs Empty => new ListPrivateNICsInvokeArgs();
    }
}
