// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Pulumi.ScalewayInstances.Action
{
    [EnumType]
    public readonly struct ScalewayInstanceV1ListServerActionsResponseActionsItem : IEquatable<ScalewayInstanceV1ListServerActionsResponseActionsItem>
    {
        private readonly string _value;

        private ScalewayInstanceV1ListServerActionsResponseActionsItem(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static ScalewayInstanceV1ListServerActionsResponseActionsItem Poweron { get; } = new ScalewayInstanceV1ListServerActionsResponseActionsItem("poweron");
        public static ScalewayInstanceV1ListServerActionsResponseActionsItem Backup { get; } = new ScalewayInstanceV1ListServerActionsResponseActionsItem("backup");
        public static ScalewayInstanceV1ListServerActionsResponseActionsItem StopInPlace { get; } = new ScalewayInstanceV1ListServerActionsResponseActionsItem("stop_in_place");
        public static ScalewayInstanceV1ListServerActionsResponseActionsItem Poweroff { get; } = new ScalewayInstanceV1ListServerActionsResponseActionsItem("poweroff");
        public static ScalewayInstanceV1ListServerActionsResponseActionsItem Terminate { get; } = new ScalewayInstanceV1ListServerActionsResponseActionsItem("terminate");
        public static ScalewayInstanceV1ListServerActionsResponseActionsItem Reboot { get; } = new ScalewayInstanceV1ListServerActionsResponseActionsItem("reboot");

        public static bool operator ==(ScalewayInstanceV1ListServerActionsResponseActionsItem left, ScalewayInstanceV1ListServerActionsResponseActionsItem right) => left.Equals(right);
        public static bool operator !=(ScalewayInstanceV1ListServerActionsResponseActionsItem left, ScalewayInstanceV1ListServerActionsResponseActionsItem right) => !left.Equals(right);

        public static explicit operator string(ScalewayInstanceV1ListServerActionsResponseActionsItem value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ScalewayInstanceV1ListServerActionsResponseActionsItem other && Equals(other);
        public bool Equals(ScalewayInstanceV1ListServerActionsResponseActionsItem other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// The action to perform on the server
    /// </summary>
    [EnumType]
    public readonly struct ServerActionAction : IEquatable<ServerActionAction>
    {
        private readonly string _value;

        private ServerActionAction(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static ServerActionAction Poweron { get; } = new ServerActionAction("poweron");
        public static ServerActionAction Backup { get; } = new ServerActionAction("backup");
        public static ServerActionAction StopInPlace { get; } = new ServerActionAction("stop_in_place");
        public static ServerActionAction Poweroff { get; } = new ServerActionAction("poweroff");
        public static ServerActionAction Terminate { get; } = new ServerActionAction("terminate");
        public static ServerActionAction Reboot { get; } = new ServerActionAction("reboot");

        public static bool operator ==(ServerActionAction left, ServerActionAction right) => left.Equals(right);
        public static bool operator !=(ServerActionAction left, ServerActionAction right) => !left.Equals(right);

        public static explicit operator string(ServerActionAction value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ServerActionAction other && Equals(other);
        public bool Equals(ServerActionAction other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    [EnumType]
    public readonly struct ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType : IEquatable<ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType>
    {
        private readonly string _value;

        private ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType LSsd { get; } = new ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType("l_ssd");
        public static ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType BSsd { get; } = new ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType("b_ssd");
        public static ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType Unified { get; } = new ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType("unified");

        public static bool operator ==(ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType left, ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType right) => left.Equals(right);
        public static bool operator !=(ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType left, ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType right) => !left.Equals(right);

        public static explicit operator string(ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType other && Equals(other);
        public bool Equals(ServerActionScalewayInstanceV1ServerActionRequestVolumeBackupTemplateVolumeType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }

    /// <summary>
    /// The task status
    /// </summary>
    [EnumType]
    public readonly struct ServerActionScalewayInstanceV1TaskStatus : IEquatable<ServerActionScalewayInstanceV1TaskStatus>
    {
        private readonly string _value;

        private ServerActionScalewayInstanceV1TaskStatus(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        public static ServerActionScalewayInstanceV1TaskStatus Pending { get; } = new ServerActionScalewayInstanceV1TaskStatus("pending");
        public static ServerActionScalewayInstanceV1TaskStatus Started { get; } = new ServerActionScalewayInstanceV1TaskStatus("started");
        public static ServerActionScalewayInstanceV1TaskStatus Success { get; } = new ServerActionScalewayInstanceV1TaskStatus("success");
        public static ServerActionScalewayInstanceV1TaskStatus Failure { get; } = new ServerActionScalewayInstanceV1TaskStatus("failure");
        public static ServerActionScalewayInstanceV1TaskStatus Retry { get; } = new ServerActionScalewayInstanceV1TaskStatus("retry");

        public static bool operator ==(ServerActionScalewayInstanceV1TaskStatus left, ServerActionScalewayInstanceV1TaskStatus right) => left.Equals(right);
        public static bool operator !=(ServerActionScalewayInstanceV1TaskStatus left, ServerActionScalewayInstanceV1TaskStatus right) => !left.Equals(right);

        public static explicit operator string(ServerActionScalewayInstanceV1TaskStatus value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ServerActionScalewayInstanceV1TaskStatus other && Equals(other);
        public bool Equals(ServerActionScalewayInstanceV1TaskStatus other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
