// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Volumes.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1VolumeTypeConstraints
    {
        /// <summary>
        /// (in bytes)
        /// </summary>
        public readonly double? Max;
        /// <summary>
        /// (in bytes)
        /// </summary>
        public readonly double? Min;

        [OutputConstructor]
        private ScalewayInstanceV1VolumeTypeConstraints(
            double? max,

            double? min)
        {
            Max = max;
            Min = min;
        }
    }
}
