# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload, Awaitable
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'ScalewayInstanceV1GetPrivateNICResponse',
    'AwaitableScalewayInstanceV1GetPrivateNICResponse',
    'get_private_nic',
    'get_private_nic_output',
]

@pulumi.output_type
class ScalewayInstanceV1GetPrivateNICResponse:
    def __init__(__self__, private_nic=None):
        if private_nic and not isinstance(private_nic, dict):
            raise TypeError("Expected argument 'private_nic' to be a dict")
        pulumi.set(__self__, "private_nic", private_nic)

    @property
    @pulumi.getter(name="privateNic")
    def private_nic(self) -> Optional['outputs.ScalewayInstanceV1PrivateNIC']:
        return pulumi.get(self, "private_nic")


class AwaitableScalewayInstanceV1GetPrivateNICResponse(ScalewayInstanceV1GetPrivateNICResponse):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ScalewayInstanceV1GetPrivateNICResponse(
            private_nic=self.private_nic)


def get_private_nic(id: Optional[builtins.str] = None,
                    server_id: Optional[builtins.str] = None,
                    zone: Optional[builtins.str] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableScalewayInstanceV1GetPrivateNICResponse:
    """
    Use this data source to access information about an existing resource.

    :param builtins.str zone: The zone you want to target
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['serverId'] = server_id
    __args__['zone'] = zone
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('scaleway-instances:private_nics:getPrivateNIC', __args__, opts=opts, typ=ScalewayInstanceV1GetPrivateNICResponse).value

    return AwaitableScalewayInstanceV1GetPrivateNICResponse(
        private_nic=pulumi.get(__ret__, 'private_nic'))
def get_private_nic_output(id: Optional[pulumi.Input[builtins.str]] = None,
                           server_id: Optional[pulumi.Input[builtins.str]] = None,
                           zone: Optional[pulumi.Input[builtins.str]] = None,
                           opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[ScalewayInstanceV1GetPrivateNICResponse]:
    """
    Use this data source to access information about an existing resource.

    :param builtins.str zone: The zone you want to target
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['serverId'] = server_id
    __args__['zone'] = zone
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('scaleway-instances:private_nics:getPrivateNIC', __args__, opts=opts, typ=ScalewayInstanceV1GetPrivateNICResponse)
    return __ret__.apply(lambda __response__: ScalewayInstanceV1GetPrivateNICResponse(
        private_nic=pulumi.get(__response__, 'private_nic')))
