# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import builtins
from enum import Enum

__all__ = [
    'ScalewayInstanceV1SnapshotState',
    'ScalewayInstanceV1SnapshotVolumeType',
    'ScalewayInstanceV1TaskStatus',
    'State',
    'VolumeType',
]


class ScalewayInstanceV1SnapshotState(builtins.str, Enum):
    AVAILABLE = "available"
    SNAPSHOTTING = "snapshotting"
    ERROR = "error"
    INVALID_DATA = "invalid_data"
    IMPORTING = "importing"
    EXPORTING = "exporting"


class ScalewayInstanceV1SnapshotVolumeType(builtins.str, Enum):
    LSSD = "l_ssd"
    BSSD = "b_ssd"
    UNIFIED = "unified"


class ScalewayInstanceV1TaskStatus(builtins.str, Enum):
    """
    The task status
    """
    PENDING = "pending"
    STARTED = "started"
    SUCCESS = "success"
    FAILURE = "failure"
    RETRY = "retry"


class State(builtins.str, Enum):
    AVAILABLE = "available"
    SNAPSHOTTING = "snapshotting"
    ERROR = "error"
    INVALID_DATA = "invalid_data"
    IMPORTING = "importing"
    EXPORTING = "exporting"


class VolumeType(builtins.str, Enum):
    LSSD = "l_ssd"
    BSSD = "b_ssd"
    UNIFIED = "unified"
