# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload, Awaitable
from .. import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'ScalewayInstanceV1ListSnapshotsResponse',
    'AwaitableScalewayInstanceV1ListSnapshotsResponse',
    'list_snapshots',
    'list_snapshots_output',
]

@pulumi.output_type
class ScalewayInstanceV1ListSnapshotsResponse:
    def __init__(__self__, snapshots=None):
        if snapshots and not isinstance(snapshots, list):
            raise TypeError("Expected argument 'snapshots' to be a list")
        pulumi.set(__self__, "snapshots", snapshots)

    @property
    @pulumi.getter
    def snapshots(self) -> Optional[Sequence['outputs.ScalewayInstanceV1Snapshot']]:
        """
        List of snapshots
        """
        return pulumi.get(self, "snapshots")


class AwaitableScalewayInstanceV1ListSnapshotsResponse(ScalewayInstanceV1ListSnapshotsResponse):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return ScalewayInstanceV1ListSnapshotsResponse(
            snapshots=self.snapshots)


def list_snapshots(zone: Optional[str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableScalewayInstanceV1ListSnapshotsResponse:
    """
    Use this data source to access information about an existing resource.

    :param str zone: The zone you want to target
    """
    __args__ = dict()
    __args__['zone'] = zone
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('scaleway-instances:snapshots:listSnapshots', __args__, opts=opts, typ=ScalewayInstanceV1ListSnapshotsResponse).value

    return AwaitableScalewayInstanceV1ListSnapshotsResponse(
        snapshots=pulumi.get(__ret__, 'snapshots'))


@_utilities.lift_output_func(list_snapshots)
def list_snapshots_output(zone: Optional[pulumi.Input[str]] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[ScalewayInstanceV1ListSnapshotsResponse]:
    """
    Use this data source to access information about an existing resource.

    :param str zone: The zone you want to target
    """
    ...
