// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Action.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1ListServerActionsResponse
    {
        public readonly ImmutableArray<Pulumi.ScalewayInstances.Action.ScalewayInstanceV1ListServerActionsResponseActionsItem> Actions;

        [OutputConstructor]
        private ScalewayInstanceV1ListServerActionsResponse(ImmutableArray<Pulumi.ScalewayInstances.Action.ScalewayInstanceV1ListServerActionsResponseActionsItem> actions)
        {
            Actions = actions;
        }
    }
}
