// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.ScalewayInstances.Action.Outputs
{

    [OutputType]
    public sealed class ScalewayInstanceV1Task
    {
        /// <summary>
        /// The description of the task
        /// </summary>
        public readonly string? Description;
        public readonly string? HrefFrom;
        public readonly string? HrefResult;
        /// <summary>
        /// The unique ID of the task
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The progress of the task in percent
        /// </summary>
        public readonly double? Progress;
        /// <summary>
        /// The task start date (RFC 3339 format)
        /// </summary>
        public readonly string? StartedAt;
        /// <summary>
        /// The task status
        /// </summary>
        public readonly Pulumi.ScalewayInstances.Action.ScalewayInstanceV1TaskStatus? Status;
        /// <summary>
        /// The task end date (RFC 3339 format)
        /// </summary>
        public readonly string? TerminatedAt;
        /// <summary>
        /// The zone in which is the task
        /// </summary>
        public readonly string? Zone;

        [OutputConstructor]
        private ScalewayInstanceV1Task(
            string? description,

            string? hrefFrom,

            string? hrefResult,

            string? id,

            double? progress,

            string? startedAt,

            Pulumi.ScalewayInstances.Action.ScalewayInstanceV1TaskStatus? status,

            string? terminatedAt,

            string? zone)
        {
            Description = description;
            HrefFrom = hrefFrom;
            HrefResult = hrefResult;
            Id = id;
            Progress = progress;
            StartedAt = startedAt;
            Status = status;
            TerminatedAt = terminatedAt;
            Zone = zone;
        }
    }
}
